### ISSUE TITLE
Show answers and comments

### ISSUE THREAD

**Issue by axross** [agnosticful/chipstackoverflow-web#121]
- [ ] Showing answers
    - [x] Answer Model (#136)
    - [x] Answer Reaction Model (#139)
    - Answer Repository Functions
        - [x] Get answers in a post (#140)
        - [x] Check if an answer is liked/disliked (#148)
    - [ ] Hooks
        - [ ] List of answers
        - [ ] Liking/Disliking answers
    - [ ] Views (#153)
- [ ] Showing comments
    - [x] Comment Model (#138)
    - [x] Comment Reaction Model (#149)
    - Comment Repository Functions
        - [ ] Get comments in a post
        - [ ] Check if a comment is liked/disliked
        - [ ] Post a comment
    - [ ] Hooks
    - [ ] Views (#153)
